services:
  nginx-fancyindex:
    image: registry.guzek.uk/nginx/nginx-fancyindex:latest
    container_name: nginx-fancyindex
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
