name: CD

permissions:
  contents: read
  id-token: write

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  push-to-registry:
    runs-on: ubuntu-latest
    environment: production
    env:
      TAG: "${{ vars.REGISTRY_HOSTNAME }}/nginx/nginx-fancyindex:latest"
    steps:
      - name: Login to container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ vars.REGISTRY_HOSTNAME }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Checkout repository code
        uses: actions/checkout@v6

      - name: Build image
        run: docker build -t "$TAG" .

      - name: Push image to registry
        run: docker push "$TAG"
